/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App;

import org.junit.Assert;
import org.junit.Test;

import java.util.List;

public class AddTaskTest {
    @Test
    public void should_add_single_word_task() {
        var expected = List.of(
                "# To be done",
                "1 Task001",
                "2 Task002",
                "5 Task005",
                "# Completed",
                "3 Task003",
                "4 Task004"
        );

        Repository.addTask("Task005");
        var tasks = Repository.getTaskLines();

        Assert.assertEquals(expected, tasks);
    }


}
