/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package App;

import java.util.Arrays;

public class App {
    public static void main(String[] args) {
        new App().run(args);
    }

    public void run(String... args){
        if (args.length <= 0) {
            return;
        }
        final Repository repository = new Repository();
        String cmd = args[0];
        String[] restCmds = Arrays.copyOfRange(args,1,args.length);
        int[] ids;
        switch (cmd){
            case "init":
                final InitCommand initCommand = new InitCommand(repository);
                initCommand.execute();
                break;
            case "list":
                final ListCommand listCommand = new ListCommand(repository);
                listCommand.execute();
                break;
            case "add":
                final AddCommand addCommand = new AddCommand(repository);
                addCommand.execute(restCmds);
                break;
            case "mark":
                final MarkCommand markCommand = new MarkCommand(repository);
                ids = Arrays.stream(restCmds).filter(item -> item.matches("\\d+")).mapToInt(Integer::parseInt).toArray();
                markCommand.execute(ids);
                break;
            case "unmark":
                final UnmarkCommand unmarkCommand = new UnmarkCommand(repository);
                ids = Arrays.stream(restCmds).filter(item -> item.matches("\\d+")).mapToInt(Integer::parseInt).toArray();
                unmarkCommand.execute(ids);
                break;
        }
    }

}
